-- =====================================================
-- Iyar Control Tower - Admin Migration Script
-- Run this in Supabase SQL Editor
-- =====================================================

-- =====================================================
-- STEP 1: Add role column to profiles table
-- =====================================================

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';

-- Create index for role lookups
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);

-- =====================================================
-- STEP 2: Create system_announcements table
-- =====================================================

CREATE TABLE IF NOT EXISTS system_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info' CHECK (type IN ('info', 'warning', 'success', 'error')),
    is_active BOOLEAN DEFAULT true,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE system_announcements ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can manage announcements
CREATE POLICY "Admins can manage announcements"
ON system_announcements FOR ALL
USING (
    EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'admin')
);

-- Policy: All authenticated users can view active announcements
CREATE POLICY "Users can view active announcements"
ON system_announcements FOR SELECT
USING (auth.uid() IS NOT NULL AND is_active = true);

-- =====================================================
-- STEP 3: Create activity_logs table for live feed
-- =====================================================

CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    details JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON activity_logs(user_id);

-- Policy: Admins can view all activity logs
CREATE POLICY "Admins can view all activity"
ON activity_logs FOR SELECT
USING (
    EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'admin')
);

-- Policy: System can insert activity logs for any user
CREATE POLICY "System can insert activity logs"
ON activity_logs FOR INSERT
WITH CHECK (true);

-- =====================================================
-- STEP 4: Create default_maintenance_templates table
-- =====================================================

CREATE TABLE IF NOT EXISTS default_maintenance_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('distance', 'time', 'both')),
    interval_km INTEGER,
    interval_months INTEGER,
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
    icon TEXT DEFAULT 'mdi-wrench',
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE default_maintenance_templates ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can manage templates
CREATE POLICY "Admins can manage templates"
ON default_maintenance_templates FOR ALL
USING (
    EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'admin')
);

-- Policy: Anyone can view active templates
CREATE POLICY "Anyone can view active templates"
ON default_maintenance_templates FOR SELECT
USING (is_active = true);

-- Insert default maintenance templates
INSERT INTO default_maintenance_templates (name, type, interval_km, interval_months, priority, icon, sort_order) VALUES
    ('تغيير زيت المحرك', 'both', 5000, 6, 'high', 'mdi-oil', 1),
    ('تغيير فلتر الزيت', 'both', 10000, 12, 'medium', 'mdi-filter', 2),
    ('تغيير فلتر الهواء', 'both', 20000, 12, 'medium', 'mdi-fan', 3),
    ('فحص الإطارات', 'both', 10000, 6, 'high', 'mdi-tire', 4),
    ('فحص البطارية', 'time', NULL, 12, 'medium', 'mdi-car-battery', 5)
ON CONFLICT DO NOTHING;

-- =====================================================
-- STEP 5: Update RLS Policies for Admin Bypass
-- =====================================================

-- Helper function to check if current user is admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM profiles 
        WHERE user_id = auth.uid() 
        AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- CARS TABLE - Admin Bypass Policies
-- =====================================================

DROP POLICY IF EXISTS "Admins have full access to cars" ON cars;
CREATE POLICY "Admins have full access to cars"
ON cars FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================
-- MAINTENANCE_TASKS TABLE - Admin Bypass Policies
-- =====================================================

DROP POLICY IF EXISTS "Admins have full access to tasks" ON maintenance_tasks;
CREATE POLICY "Admins have full access to tasks"
ON maintenance_tasks FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================
-- MAINTENANCE_RECORDS TABLE - Admin Bypass Policies
-- =====================================================

DROP POLICY IF EXISTS "Admins have full access to records" ON maintenance_records;
CREATE POLICY "Admins have full access to records"
ON maintenance_records FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================
-- DOCUMENTS TABLE - Admin Bypass Policies
-- =====================================================

DROP POLICY IF EXISTS "Admins have full access to documents" ON documents;
CREATE POLICY "Admins have full access to documents"
ON documents FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================
-- ODOMETER_READINGS TABLE - Admin Bypass Policies
-- =====================================================

DROP POLICY IF EXISTS "Admins have full access to readings" ON odometer_readings;
CREATE POLICY "Admins have full access to readings"
ON odometer_readings FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================
-- PROFILES TABLE - Admin Bypass Policies
-- =====================================================

DROP POLICY IF EXISTS "Admins have full access to profiles" ON profiles;
CREATE POLICY "Admins have full access to profiles"
ON profiles FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================
-- STEP 6: Create Activity Log Trigger Functions
-- =====================================================

-- Function to log car additions
CREATE OR REPLACE FUNCTION log_car_activity()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO activity_logs (user_id, action, entity_type, entity_id, details)
    VALUES (
        NEW.user_id,
        CASE TG_OP
            WHEN 'INSERT' THEN 'added_car'
            WHEN 'UPDATE' THEN 'updated_car'
            ELSE 'modified_car'
        END,
        'car',
        NEW.id,
        jsonb_build_object('make', NEW.make, 'model', NEW.model, 'year', NEW.year)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to log maintenance record additions
CREATE OR REPLACE FUNCTION log_maintenance_activity()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO activity_logs (user_id, action, entity_type, entity_id, details)
    VALUES (
        NEW.user_id,
        'recorded_maintenance',
        'maintenance_record',
        NEW.id,
        jsonb_build_object('task_name', NEW.task_name, 'cost', NEW.cost)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to log odometer updates
CREATE OR REPLACE FUNCTION log_odometer_activity()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO activity_logs (user_id, action, entity_type, entity_id, details)
    VALUES (
        NEW.user_id,
        'updated_odometer',
        'odometer_reading',
        NEW.id,
        jsonb_build_object('reading', NEW.reading)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create triggers
DROP TRIGGER IF EXISTS trigger_log_car ON cars;
CREATE TRIGGER trigger_log_car
    AFTER INSERT OR UPDATE ON cars
    FOR EACH ROW
    EXECUTE FUNCTION log_car_activity();

DROP TRIGGER IF EXISTS trigger_log_maintenance ON maintenance_records;
CREATE TRIGGER trigger_log_maintenance
    AFTER INSERT ON maintenance_records
    FOR EACH ROW
    EXECUTE FUNCTION log_maintenance_activity();

DROP TRIGGER IF EXISTS trigger_log_odometer ON odometer_readings;
CREATE TRIGGER trigger_log_odometer
    AFTER INSERT ON odometer_readings
    FOR EACH ROW
    EXECUTE FUNCTION log_odometer_activity();

-- =====================================================
-- DONE! تم الانتهاء
-- =====================================================
-- After running this script:
-- 1. Set your user role to admin:
--    UPDATE profiles SET role = 'admin' WHERE user_id = 'YOUR-USER-ID';
-- 2. Access the Control Tower at /control-tower-iyar
-- =====================================================
