-- =====================================================
-- 3YAR App - Notifications Migration
-- =====================================================

-- 1. Create announcements table
CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info' CHECK (type IN ('info', 'warning', 'success', 'error')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

-- 2. Create announcement_reads table
CREATE TABLE IF NOT EXISTS announcement_reads (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    announcement_id BIGINT REFERENCES announcements(id) ON DELETE CASCADE,
    read_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, announcement_id)
);

-- 3. Enable RLS
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcement_reads ENABLE ROW LEVEL SECURITY;

-- 4. Policies for announcements
CREATE POLICY "Anyone can view announcements"
ON announcements FOR SELECT
USING (true);

CREATE POLICY "Admins can manage announcements"
ON announcements FOR ALL
USING (EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'admin'));

-- 5. Policies for announcement_reads
CREATE POLICY "Users can manage their own reads"
ON announcement_reads FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 6. Insert sample announcement (optional)
-- INSERT INTO announcements (title, message, type) VALUES ('أهلاً بكم في عيار', 'تم تفعيل نظام التنبيهات الجديد.', 'success');
