-- =====================================================
-- 3YAR App - Complete Supabase Database Schema
-- قاعدة بيانات تطبيق عيار الكاملة
-- Run this SQL in Supabase SQL Editor
-- =====================================================

-- =====================================================
-- STEP 1: Create Tables (إنشاء الجداول)
-- =====================================================

-- جدول السيارات
CREATE TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    plate_number TEXT NOT NULL,
    color TEXT DEFAULT '',
    vin TEXT DEFAULT '',
    initial_odometer INTEGER DEFAULT 0,
    current_odometer INTEGER DEFAULT 0,
    image TEXT,
    notes TEXT DEFAULT '',
    public_share_enabled BOOLEAN DEFAULT false,
    share_token UUID DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول مهام الصيانة
CREATE TABLE IF NOT EXISTS maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('distance', 'time', 'both')),
    interval_km INTEGER,
    interval_months INTEGER,
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
    is_recurring BOOLEAN DEFAULT true,
    last_maintenance_date TIMESTAMPTZ,
    last_maintenance_odometer INTEGER,
    snoozed_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول سجلات الصيانة
CREATE TABLE IF NOT EXISTS maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
    task_id BIGINT REFERENCES maintenance_tasks(id) ON DELETE SET NULL,
    task_name TEXT NOT NULL,
    date TIMESTAMPTZ DEFAULT NOW(),
    odometer_reading INTEGER DEFAULT 0,
    cost NUMERIC(10,2) DEFAULT 0,
    service_center TEXT DEFAULT '',
    invoice_number TEXT DEFAULT '',
    invoice_image TEXT,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول الوثائق
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    document_number TEXT DEFAULT '',
    issue_date DATE,
    expiry_date DATE,
    image TEXT,
    notes TEXT DEFAULT '',
    reminder_days INTEGER DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول قراءات العداد
CREATE TABLE IF NOT EXISTS odometer_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
    reading INTEGER NOT NULL,
    date TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- STEP 2: Create Indexes (إنشاء الفهارس)
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_cars_user_id ON cars(user_id);
CREATE INDEX IF NOT EXISTS idx_cars_share_token ON cars(share_token);
CREATE INDEX IF NOT EXISTS idx_maintenance_tasks_user_id ON maintenance_tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_tasks_car_id ON maintenance_tasks(car_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_user_id ON maintenance_records(user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_car_id ON maintenance_records(car_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_date ON maintenance_records(date);
CREATE INDEX IF NOT EXISTS idx_documents_user_id ON documents(user_id);
CREATE INDEX IF NOT EXISTS idx_documents_car_id ON documents(car_id);
CREATE INDEX IF NOT EXISTS idx_documents_expiry_date ON documents(expiry_date);
CREATE INDEX IF NOT EXISTS idx_odometer_readings_user_id ON odometer_readings(user_id);
CREATE INDEX IF NOT EXISTS idx_odometer_readings_car_id ON odometer_readings(car_id);
CREATE INDEX IF NOT EXISTS idx_odometer_readings_date ON odometer_readings(date);

-- =====================================================
-- STEP 3: Enable Row Level Security (تفعيل RLS)
-- =====================================================

ALTER TABLE cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE odometer_readings ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- STEP 4: Drop Old Policies (حذف السياسات القديمة)
-- =====================================================

DROP POLICY IF EXISTS "Allow all for cars" ON cars;
DROP POLICY IF EXISTS "Allow all for maintenance_tasks" ON maintenance_tasks;
DROP POLICY IF EXISTS "Allow all for maintenance_records" ON maintenance_records;
DROP POLICY IF EXISTS "Allow all for documents" ON documents;
DROP POLICY IF EXISTS "Allow all for odometer_readings" ON odometer_readings;

DROP POLICY IF EXISTS "Users can manage their own cars" ON cars;
DROP POLICY IF EXISTS "Public can view shared cars" ON cars;
DROP POLICY IF EXISTS "Users can manage their own tasks" ON maintenance_tasks;
DROP POLICY IF EXISTS "Public can view tasks of shared cars" ON maintenance_tasks;
DROP POLICY IF EXISTS "Users can manage their own records" ON maintenance_records;
DROP POLICY IF EXISTS "Users can manage their own documents" ON documents;
DROP POLICY IF EXISTS "Public can view documents of shared cars" ON documents;
DROP POLICY IF EXISTS "Users can manage their own readings" ON odometer_readings;
DROP POLICY IF EXISTS "Public can view odometer of shared cars" ON odometer_readings;

-- =====================================================
-- STEP 5: Create Security Policies (إنشاء سياسات الأمان)
-- =====================================================

-- سياسات جدول السيارات
CREATE POLICY "Users can manage their own cars"
ON cars FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Public can view shared cars"
ON cars FOR SELECT 
USING (public_share_enabled = true);

-- سياسات جدول مهام الصيانة
CREATE POLICY "Users can manage their own tasks"
ON maintenance_tasks FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Public can view tasks of shared cars"
ON maintenance_tasks FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM cars 
    WHERE cars.id = maintenance_tasks.car_id 
    AND cars.public_share_enabled = true
  )
);

-- سياسات جدول سجلات الصيانة
CREATE POLICY "Users can manage their own records"
ON maintenance_records FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- سياسات جدول الوثائق
CREATE POLICY "Users can manage their own documents"
ON documents FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Public can view documents of shared cars"
ON documents FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM cars 
    WHERE cars.id = documents.car_id 
    AND cars.public_share_enabled = true
  )
);

-- سياسات جدول قراءات العداد
CREATE POLICY "Users can manage their own readings"
ON odometer_readings FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Public can view odometer of shared cars"
ON odometer_readings FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM cars 
    WHERE cars.id = odometer_readings.car_id 
    AND cars.public_share_enabled = true
  )
);

-- =====================================================
-- STEP 6: Create Triggers (إنشاء الـ Triggers)
-- =====================================================

-- دالة تعيين user_id تلقائياً
CREATE OR REPLACE FUNCTION set_user_id()
RETURNS TRIGGER AS $$
BEGIN
    NEW.user_id = auth.uid();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- دالة تحديث updated_at تلقائياً
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers لتعيين user_id
DROP TRIGGER IF EXISTS set_cars_user_id ON cars;
CREATE TRIGGER set_cars_user_id
    BEFORE INSERT ON cars
    FOR EACH ROW
    EXECUTE FUNCTION set_user_id();

DROP TRIGGER IF EXISTS set_tasks_user_id ON maintenance_tasks;
CREATE TRIGGER set_tasks_user_id
    BEFORE INSERT ON maintenance_tasks
    FOR EACH ROW
    EXECUTE FUNCTION set_user_id();

DROP TRIGGER IF EXISTS set_records_user_id ON maintenance_records;
CREATE TRIGGER set_records_user_id
    BEFORE INSERT ON maintenance_records
    FOR EACH ROW
    EXECUTE FUNCTION set_user_id();

DROP TRIGGER IF EXISTS set_documents_user_id ON documents;
CREATE TRIGGER set_documents_user_id
    BEFORE INSERT ON documents
    FOR EACH ROW
    EXECUTE FUNCTION set_user_id();

DROP TRIGGER IF EXISTS set_readings_user_id ON odometer_readings;
CREATE TRIGGER set_readings_user_id
    BEFORE INSERT ON odometer_readings
    FOR EACH ROW
    EXECUTE FUNCTION set_user_id();

-- Triggers لتحديث updated_at
DROP TRIGGER IF EXISTS update_cars_updated_at ON cars;
CREATE TRIGGER update_cars_updated_at
    BEFORE UPDATE ON cars
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS update_documents_updated_at ON documents;
CREATE TRIGGER update_documents_updated_at
    BEFORE UPDATE ON documents
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- =====================================================
-- DONE! تم الانتهاء
-- =====================================================
-- ملاحظة: بعد تشغيل هذا الكود، تأكد من:
-- 1. تفعيل Email Auth في: Authentication > Providers > Email
-- 2. التحقق من إنشاء الجداول في: Table Editor
-- 3. التحقق من السياسات في: Authentication > Policies
-- =====================================================
